sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

addons:
  apt:
    packages:
      - lynx

before_script:
    - sh travis_local_properties.sh
    - sh travis_ga_properties.sh

script:
  - ./gradlew build
  - ./gradlew lint
  - ./gradlew testPlaystoreDebugUnitTest
  - ./gradlew testFossDebugUnitTest

after_failure:
 - if [ -f /home/travis/build/jayrambhia/MovieRatings/app/build/reports/lint-results.html ]; then lynx -dump /home/travis/build/jayrambhia/MovieRatings/app/build/reports/lint-results.html; fi
